# Generated by Django 4.2.4 on 2023-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_player_tournament_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='in_round',
            field=models.IntegerField(default=0, max_length=64),
        ),
    ]
