# Generated by Django 4.2.4 on 2023-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_in_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='states',
            field=models.CharField(choices=[('1', 'user'), ('2', 'company')], default='1', max_length=160),
        ),
    ]
