# Generated by Django 4.2.5 on 2023-09-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_is_completed'),
        ('tournament', '0005_alter_profile_states'),
    ]

    operations = [
    ]
