# Generated by Django 4.2.5 on 2023-09-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournament_players_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players_list',
        ),
        migrations.CreateModel(
            name='TournamentPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.profile')),
                ('tourmnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
