# Generated by Django 4.2.5 on 2023-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_tournament_players_list_tournamentplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_players',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
