# Generated by Django 4.2.5 on 2023-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_remove_tournament_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='in_round',
            field=models.IntegerField(default=0),
        ),
    ]
