# Generated by Django 4.2.5 on 2023-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_tournament_game_alter_tournament_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='trpoy_for_tourment',
            field=models.IntegerField(choices=[(1000, 'Bronze'), (2000, 'Sliver'), (3000, 'Gold')], default=1000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.IntegerField(choices=[(1, 'Chess'), (2, 'Takken'), (3, 'x&o'), (4, 'Call Of Duty'), (5, 'FIFA24')], default=1),
        ),
    ]
