# Generated by Django 4.2.5 on 2023-09-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_tournament_trpoy_for_tourment_alter_tournament_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_rank',
            field=models.CharField(choices=[('1', 'user'), ('2', 'company')], default='1', max_length=160),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_tournament', to='tournament.profile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tournaments', to='tournament.profile'),
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('tournament', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournament.profile')),
            ],
        ),
    ]
