# Generated by Django 4.2.5 on 2023-09-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_rename_trpoy_for_tourment_tournament_trophy_for_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_completed',
        ),
    ]
