# Generated by Django 4.2.5 on 2023-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_tournament_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Player'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_rank',
            field=models.CharField(choices=[('nor', 'Normal'), ('pro', 'Professional'), ('master', 'Master')], default='1', max_length=160),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='trophy_for_tournament',
            field=models.IntegerField(choices=[(100, 'Bronze'), (200, 'Sliver'), (300, 'Gold')], default=1000),
        ),
    ]
