# Generated by Django 4.2.4 on 2023-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_alter_tournament_trophy_for_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
