# Generated by Django 4.2.4 on 2023-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_tournament_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_rank',
            field=models.CharField(choices=[('nor', 'Normal'), ('pro', 'Professional'), ('master', 'Master')], default='nor', max_length=160),
        ),
    ]
