# Generated by Django 4.2.5 on 2023-09-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0003_trophy_tournament_trophy_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trophy',
        ),
    ]
